export const APP_STATE_IDLE = 'APP_STATE_IDLE'
export const APP_STATE_CHECKING_CAN_INCREMENT = 'APP_STATE_CHECKING_CAN_INCREMENT'

export const COUNT_INCREMENT_REQUESTED = 'COUNT_INCREMENT_REQUESTED'
export const COUNT_INCREMENT_APPROVED = 'COUNT_INCREMENT_APPROVED'
export const COUNT_INCREMENT_DENIED = 'COUNT_INCREMENT_DENIED'
export const COUNT_INCREMENT_REQUEST_FAILED = 'COUNT_INCREMENT_REQUEST_FAILED'
