export const VIDEO_LIST_PAGE_NAVIGATED_TO_WITHOUT_DATA = 'VIDEO_LIST_PAGE_NAVIGATED_TO_WITHOUT_DATA'
export const VIDEO_LIST_DATA_FETCHED = 'VIDEO_LIST_DATA_FETCHED'
export const VIDEO_DETAIL_LINK_CLICKED = 'VIDEO_DETAIL_LINK_CLICKED'
